AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"
    - "config/environments/**/*"
    - "config/application.rb"
    - "config/initializers/backtrace_silencers.rb"
    - "config/initializers/session_store.rb"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  CountComments: false
  Max: 125

Metrics/ClassLength:
  CountComments: false
  Max: 175

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/AbcSize:
  Max: 20

NumericLiterals:
  Enabled: false

Documentation:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true
