Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  CountComments: false
  Max: 125

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/AbcSize:
  Max: 20

NumericLiterals:
  Enabled: false

Documentation:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true
