AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "activemodel-datastore.gemspec"
    - "Rakefile"
    - "lib/active_model/datastore/version.rb"
    - "test/support/datastore_example_rails_app/bin/**/*"
    - "test/support/datastore_example_rails_app/config/environments/**/*"
    - "test/support/datastore_example_rails_app/config/application.rb"
    - "test/support/datastore_example_rails_app/config/initializers/backtrace_silencers.rb"
    - "test/support/datastore_example_rails_app/config/initializers/session_store.rb"
    - "test/support/datastore_example_rails_app/vendor/**/*"
    - "test/support/datastore_example_rails_app/Gemfile"
    - "vendor/**/*"

#################### Layout ##########################

Layout/LineLength:
  Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

##################### Lint ###########################

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

#################### Style ###########################

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent

Style/YodaCondition:
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Max: 150

Metrics/ClassLength:
  CountComments: false
  Max: 175
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - "test/**/*"

Metrics/AbcSize:
  Max: 26

Naming/VariableNumber:
  Enabled: false
