AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "activemodel-datastore.gemspec"
    - "Rakefile"
    - "lib/active_model/datastore/version.rb"
    - "test/support/cloud_datastore_rails_app/bin/**/*"
    - "test/support/cloud_datastore_rails_app/config/environments/**/*"
    - "test/support/cloud_datastore_rails_app/config/application.rb"
    - "test/support/cloud_datastore_rails_app/config/initializers/backtrace_silencers.rb"
    - "test/support/cloud_datastore_rails_app/config/initializers/session_store.rb"
    - "test/support/cloud_datastore_rails_app/vendor/**/*"
    - "test/support/cloud_datastore_rails_app/Gemfile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  CountComments: false
  Max: 150

Metrics/ClassLength:
  CountComments: false
  Max: 175
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - "test/**/*"

Metrics/AbcSize:
  Max: 25

NumericLiterals:
  Enabled: false

Documentation:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true

Style/VariableNumber:
  Enabled: false