AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"
    - "config/environments/**/*"
    - "config/application.rb"
    - "config/initializers/backtrace_silencers.rb"
    - "config/initializers/session_store.rb"
    - "vendor/**/*"
    - "Gemfile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  CountComments: false
  Max: 150

Metrics/ClassLength:
  CountComments: false
  Max: 175
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - "test/**/*"

Metrics/AbcSize:
  Max: 25

NumericLiterals:
  Enabled: false

Documentation:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true

Style/VariableNumber:
  Enabled: false