language: ruby
cache:
  bundler: true
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH:
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install cloud-datastore-emulator
  - export PATH="$HOME/google-cloud-sdk/platform/cloud-datastore-emulator:$PATH"
  - cloud_datastore_emulator create tmp/local_datastore
  - cloud_datastore_emulator start --port=8180 tmp/local_datastore &
